import { readFileSync } from 'node:fs';

import {
    resolveGitHubRepository,
    resolvePublishChannel,
    type PackageMetadata,
} from './electron/main/updates/releaseConfig';

import type { Configuration } from 'electron-builder';

function readPackageMetadata(): PackageMetadata {
    const packagePath = new URL('./package.json', import.meta.url);
    return JSON.parse(readFileSync(packagePath, 'utf8')) as PackageMetadata;
}

const metadata = readPackageMetadata();
const version = metadata.version ?? '';
const publishChannel = resolvePublishChannel(version, process.env['UPDATE_CHANNEL']);
const github = resolveGitHubRepository(metadata.repository);
const shouldNotarize = Boolean(
    process.env['APPLE_API_KEY'] && process.env['APPLE_API_KEY_ID'] && process.env['APPLE_API_ISSUER']
);

const config: Configuration = {
    appId: 'com.example.electron-template',
    productName: 'Electron Template',

    files: ['dist', 'dist-electron'],
    // Product migrations generated by Drizzle Kit are copied outside ASAR so
    // the opt-in runtime migrator can read them from process.resourcesPath.
    // The checked-in scaffold is empty, so this adds nothing until tables exist.
    extraResources: [
        {
            from: 'electron/main/data/migrations',
            to: 'migrations',
            filter: ['**/*.sql', '**/*.json'],
        },
    ],
    asar: true,
    electronUpdaterCompatibility: '>=2.16',
    detectUpdateChannel: false,

    electronFuses: {
        runAsNode: false,
        enableCookieEncryption: true,
        enableNodeOptionsEnvironmentVariable: false,
        enableNodeCliInspectArguments: false,
        enableEmbeddedAsarIntegrityValidation: true,
        onlyLoadAppFromAsar: true,
        loadBrowserProcessSpecificV8Snapshot: false,
        // The renderer is served from the privileged app:// scheme, so file://
        // pages never need their legacy extra privileges.
        grantFileProtocolExtraPrivileges: false,
    },

    directories: {
        output: 'release/${version}',
        buildResources: '.',
    },

    icon: 'src/assets/appicon.png',

    mac: {
        category: 'public.app-category.developer-tools',
        hardenedRuntime: true,
        notarize: shouldNotarize,
        target: [
            { target: 'dmg', arch: ['x64', 'arm64', 'universal'] },
            { target: 'pkg', arch: ['x64', 'arm64', 'universal'] },
            { target: 'zip', arch: ['x64', 'arm64', 'universal'] },
        ],
        artifactName: 'Electron-Template-${version}-macOS-${arch}.${ext}',
    },

    win: {
        target: [{ target: 'nsis', arch: ['x64'] }],
        artifactName: 'Electron-Template-${version}-Windows-${arch}-Setup.${ext}',
        signAndEditExecutable: true,
    },

    nsis: {
        oneClick: true,
        perMachine: false,
        allowToChangeInstallationDirectory: false,
        deleteAppDataOnUninstall: false,
    },

    linux: {
        category: 'Development',
        target: [
            { target: 'AppImage', arch: ['x64', 'arm64'] },
            { target: 'deb', arch: ['x64', 'arm64'] },
            { target: 'rpm', arch: ['x64', 'arm64'] },
        ],
        artifactName: 'Electron-Template-${version}-Linux-${arch}.${ext}',
    },

    publish: [
        {
            provider: 'github',
            owner: github.owner,
            repo: github.repo,
            channel: publishChannel,
            protocol: 'https',
        },
    ],
};

export default config;
